POST http://localhost:3000/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "acddca232",
  "email": "email"
}

###

POST http://localhost:3000/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "username": "admin",
  "password": "acddca232",
  "email": "email1@email.com"
}

###

GET  http://localhost:3000/api/user/profile HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMxZTFmNWNjLWRkMzQtNDNkNi05MDU4LWE3ZjE4NWMxNDFjZiIsImlhdCI6MTU5NjgwNDk2MywiZXhwIjoxNTk2ODA1ODYzfQ.Ff4MXx-mvAQ_8LhEcyllrjByy_EoDHbeA_XZvYP_Tnk
